{application,graphvix,
             [{applications,[kernel,stdlib,elixir,logger,ex_doc,
                             mix_test_watch,stream_data,credo]},
              {description,"Elixir interface for Graphviz"},
              {modules,['Elixir.Graphvix','Elixir.Graphvix.DotHelpers',
                        'Elixir.Graphvix.Graph','Elixir.Graphvix.HTMLRecord',
                        'Elixir.Graphvix.Record',
                        'Elixir.Graphvix.Record.Port',
                        'Elixir.Graphvix.RecordSubset',
                        'Elixir.Graphvix.Subgraph']},
              {registered,[]},
              {vsn,"1.0.0"}]}.
